language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - DJANGO_VERSION=5.1.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script: python manage.py test
