dist: focal
language: python
python:
  - "3.12"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - black --check .
  - flake8 .
script: 
  - coverage run --source='.' manage.py test
  - coverage report -m
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-west-2"
  app: "swe-polls"
  env: "swe-polls-dev"
  bucket_name: "elasticbeanstalk-us-west-2-908027391593"
  on:
    branch: master
